[package]
name = "invariant"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = { version = "0.9.3", default-features = false }
num-traits = "0.2.14"
uint = { version = "0.9", default-features = false }
odra = { git = "https://github.com/odradev/odra.git", branch = "release/0.4.0", default-features = false }
odra-modules = { git = "https://github.com/odradev/odra.git", branch = "release/0.4.0", default-features = false }
decimal = { path = "src/decimal" }
traceable_result = { path = "src/traceable_result" }

[features]
default = ["mock-vm"]
mock-vm = ["odra/mock-vm", "odra-modules/mock-vm"]
casper = ["odra/casper", "odra-modules/casper"]
