name: markdown-skip

on:
  push:
    branches:
      - "dev"
      - "feat-*"
      - "release-*"
    paths:
      - '**.md'

  pull_request:
    branches:
      - "dev"
      - "feat-*"
      - "release-*"
    paths:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [16.x]

    steps:
      - run: 'echo "Markdown only change, no lints required"'
